### ISSUE TITLE
add goto option which can be used instead of content

### ISSUE THREAD

**Issue by Ognian** [isneezy/pdf-generator-service#228]
At the moment html is passed via the `content` option.
I would suggest to also add a `goto` option, which if present issues [page.goto ](https://pptr.dev/#?product=Puppeteer&version=v10.0.0&show=api-pagegotourl-options)

This should make using a TOC template easier to.

Thanks
Ognian

**Comment by isneezy** [comment]
Hi, thanks for your suggestion, this is something really useful. I’ll see if I can find time to implement this, I’d be very happy if you can issue a PR for this
